### PR TITLE
[WIP] Main TOC across files

### PR DESCRIPTION
**Pull request by jmanuel1**
This pull request would close issue #93.

Right now it generates a file `main_toc.md` whenever a `--main` option as passed. Any comments appreciated.

### CODE REVIEW

**Comment by scozv** [comment]
I am looking forward to the accept of this PR.

But, how do we use it, I read your code, and didn't find the parameter for this feature.

Is there any parameter we need, such as:

```
doctoc --main-file "main.md" --files "a.md, b.md, c.md, d.md"
// put toc form {a, b, c, d} into main.md
```

**Comment by jmanuel1** [comment]
Sorry if it isn't exactly clear at the moment.

Let's say you run `doctoc --main a.md b.md`. Then a file `main_toc.md` will be generated in the current directory that contains the main TOC. The files a.md and b.md will also be toc'd as well. It's not very flexible, as I wanted to work out the logic and get comments on it before going any further.

**Comment by fbehrens** [comment]
I just stumbled about `tocdoc` as I have implemented this feature in powershell. May I suggest the following simple API. Make it as  an optional  additional parameter iE `-main` 

Such that
    
    doctoc doc -main readme.md 

will create a consolidated TOC of all markdown documents in `readme.md`

**Comment by karfau** [comment]
So for brainstorming and clarifications:
#93 is not very specific about the expected output.
I can imagine the following formats:
1. A deeply nested combined TOC from all tocs that doctoc found from the arguments.
2. A toc derived from the folder/file structure that just links to every file, every folder level would be one level of nesting. (something we have implemented using bash, t generate an index over all [markdown] files, independent of contained TOC.)

maybe @ramyadhadidi as the author of the issue could provide some input on what he wanted to request.

I think in any case it would be nice to allow specifying how deep you want to go for nesting.

I agree with earlier comments that it would be nice to be able to specify the filename for the output.

Another topic is, if this would be bloating the options and capabilities of `doctoc` to much (in the sense of providing tools that can do one thing and do it well), maybe it could be a second binary that reuses code for iterating and parsing the files, but the indexing of markdown files is basically a different goal then generating a TOC from the content a single file.

**Comment by ramyadhadidi** [comment]
When opening the issue, I had format 1 in my mind. However, format 2 is also interesting.

**Comment by jmanuel1** [comment]
Okay, you should be able to specify the file where the main TOC goes now.

**Comment by kingbangla191** [comment]
Okay, you should be able to specify the file where the main TOC goes now.
Comment on pull request

**Comment by tomdavidson** [comment]
Thank you @thlorenz  and @jmanuel1 this is just the tool I have been looking for :D 

I merged jmanuel1/issue-93 with my fork of doctoc  and run
```shell
$ doctoc --gitlab --main README.md --gitlab --maxlevel 1 data/

DocToccing "data/" and its sub directories for gitlab.com.

Found concourse-rebuild.md, runbook-add.md, runbook-modify.md in "data/"

==================

"data/concourse-rebuild.md" will be updated
"data/runbook-add.md" will be updated
"data/runbook-modify.md" will be updated

Everything is OK.
```

But it isn't quite OK. The README.md is buggered up (and over written). I should have three different top-levels, each with four 2nd levels. Also, what is "mdundefined" all about? 

```md
- [Concourse Rebuild](data/concourse-rebuild.mdundefined)
  - [Issues Addressed](data/concourse-rebuild.mdundefined)mdundefined
  - [Business Value](data/concourse-rebuild.mdundefined)
  - [Technical Landscape](data/concourse-rebuild.mdundefined)
  - [Prerequisites / Requirements](data/concourse-rebuild.mdundefined)
  - [Steps](data/concourse-rebuild.mdundefined)- [Runbook Add](data/runbook-add.mdundefined)
  - [Business Value](data/runbook-add.mdundefined)
  - [Technical Landscape](data/runbook-add.mdundefined)
  - [Prerequisites / Requirements](data/runbook-add.mdundefined)
  - [Steps](data/runbook-add.mdundefined)- [Runbook Modify](data/runbook-modify.mdundefined)
  - [Business Value](data/runbook-modify.mdundefined)
  - [Technical Landscape](data/runbook-modify.mdundefined)
  - [Prerequisites / Requirements](data/runbook-modify.mdundefined)
  - [Steps](data/runbook-modify.mdundefined)
```

**Comment by jmanuel1** [comment]
As for the README being over-written... I actually wrote the code that way. (But I'll change that if that is the expected behavior.)

`undefined` appears seemingly because there was a change in markdown-to-ast that broke the main TOC generation. Specifically, the link nodes from the parser use a `url` instead of an `href` property to store links. That should be fixed now.

As for the levels being messed up... upon further inspection of your output, it seems that newlines are missing before the top-levels. Could I have the files you were trying to toc so I can reproduce your issue?

**Comment by jmanuel1** [comment]
@karfau You mentioned being able to specify how deep the main TOC should go. But should that be a separate option from the other TOCs? For example, if one wants the main TOC to be shallower than the others?

**Comment by tomdavidson** [comment]
Thanks for continuing to work on this. I can handle producing a separate toc file and then using another tool to merge, but doctoc has the toc location/insert feature that would be nice to use in this PR too.

In my readme that is main, I expected the following to be used:
```md
<!-- START doctoc -->
<!-- END doctoc -->
```

Thanks for continuing to work on this. My try had three files all three from this template [gist](https://gist.github.com/tomdavidson/e8e17330682739f86b3af38c037fa12c).  The example above is missing the title level for all run books but the first. Maybe the AST/undefined issue?

**Comment by karfau** [comment]
Do I understand correctly that you are heading for option 1 [described here](https://github.com/thlorenz/doctoc/pull/113#issuecomment-343603274)?

And do I understand correctly that in a single run when using the new `--main` argument it generates the main file AND updates all the tocs?

In that case (both questions answered with yes) I see the following options (ordered by personal preference):
- When using the `--main` argument only generates the main toc for the files but doesn't update all tocs.
  This way you can use the existing option `--maxlevel`.
- You ignore the `--maxlevel` option for the main toc (that additional option can still be added in a later PR)
- You provide an additional option for the maxlevel in the main toc

Did that answer [your question](https://github.com/thlorenz/doctoc/pull/113#issuecomment-377102160)?

**Comment by jmanuel1** [comment]
@karfau Yes and yes, you do understand correctly.

I also prefer your first option. Perhaps the others can have a bit of say on this.

**Comment by jmanuel1** [comment]
@tomdavidson Did your missing top-levels issue appear when you ran doctoc on a directory, similar to `node doctoc runbooks\ --main main.md`?

**Comment by tomdavidson** [comment]
No, I gave up on doctoc and doing something lame with pandoc. I can try again with your more recent updates to this PR.

**Comment by tomdavidson** [comment]
@karfau Can remark-toc creates a toc from a directory of files? Insert the toc into an existing README.md? This project has open issues and PRs that seem a bit old, but that is just the way it goes sometimes right? There are lots of open PRs everywhere with lots of revisions and discussion over time, especially when its new features and not a fix.

@thlorenz Perhaps there is need and room for additional maintainers?

**Comment by karfau** [comment]
@tomdavidson I'm pretty sure that remark-toc is only working on the level of a single markdown file, but since the underlying achritecture is able to provide an AST for the markdown, it would be possible to write a plugin that could provide this functionality.
doctoc and remark-toc are not exactly matches, but I was actually tire of waiting for a PR to land over half a year. And there has not been a reply to #148 in 20 days now.

I know there is no way to enforce maintainance but I found a toll that has a vivid community and a solid architechture so I decided to switch. not that I would suggest this for everybody.

**Comment by jmanuel1** [comment]
For those of you that are still here:

* How should file paths in TOC anchors be normalized? Right now my doctoc branch basically uses the paths given to it as they are, only changing the path separator to the system one if running on a directory. This is because I haven't explicitly handled such things.
* How should the main TOC be ordered if it is of a directory?

**Comment by jmanuel1** [comment]
I'm thinking the path separator ought to always be `/` since these paths are being used in links. I'm not sure about the ordering of files in a directory though. Should it be lexicographical order?

**Comment by rohanprasad** [comment]
Looks like this has been abandoned. I was looking for this feature, let me know if I can contribute to this in some way.

**Comment by jmanuel1** [comment]
I have not touched this code in years. If @rohanprasad or anyone else wishes to, you can continue on my work, the latest of which was in my [issue-93-better](https://github.com/jmanuel1/doctoc/tree/issue-93-better) branch, or start your own work. Since I currently don't have plans to develop this pull request, I will close it.

**Pull request closed without merging**
