### PR TITLE
Added --stdout flag to output single file transforms to stdout.

### PR DESCRIPTION
**Pull request by citruz**
Added --stdout flag to output single file transforms to stdout, so that it can be used in conjunction with other tools.
Replacement for #40

### CODE REVIEW

**Comment by thlorenz** [comment]
This breaks some logging features using format options like `'%s'`.
Please fix those, i.e. by using the `format` function found in the node core `util` module.

Example output of breakage:

```
➝  node doctoc.js README.md

DocToccing single file "%s" for %s.

==================

"%s" will be updated

Everything is OK.
```

The `%s` should actually be the filename.

**Comment by citruz** [comment]
You're absolutely right, sorry for that. I fixed this and another bug produced by me.

**Comment by thlorenz** [comment]
Any news on this?

**Comment by thlorenz** [comment]
Closing due to inactivity. Please open another PR that takes my suggestions into account if you're still interested.

**Pull request closed without merging**
