### PR TITLE
Handle file skipping internally

### PR DESCRIPTION
**Pull request by zyskowsk**
The current solution for skipping files is to have a system utility such
as `ack` handle the searching for you.  This is not ideal because it
makes the documentation not as clear and ads a dependancies in some
cases.

Here we have the library handle skipping files, but simply not
transforming files that contain the tag

### CODE REVIEW

**Comment by wolfcon** [comment]
@thlorenz plz accept this.

**Review by AndrewSouthpaw — CHANGES_REQUESTED** [review]
Looks like a step in a great direction, thanks! Please add a test to assert behavior, and I think we'll be all set with this.

**Comment by wolfcon** [comment]
@AndrewSouthpaw I just add a test for this PR. [Check it out](https://github.com/thlorenz/doctoc/pull/206)

**Review by AndrewSouthpaw — APPROVED** [review]
LGTM, nice work!

**Pull request merged**
