### PR TITLE
change badge to svg

### PR DESCRIPTION
**Pull request by a0viedo**

### CODE REVIEW

**Comment by jez** [comment]
What's the reasoning behind this?

**Comment by a0viedo** [comment]
oh, it looks much better

**Comment by jez** [comment]
Oh I see. Thanks!

**Comment by cztomczak** [comment]
SVG badges look bad in Chrome on Linux, see screenshot below. On Mac/Windows it looks okay.
svg-badge-in-chrome-on-linux

**Comment by a0viedo** [comment]
@cztomczak can't reproduce right now but isn't a good thing to ask Google for a bugfix?

**Comment by jez** [comment]
I was thinking something similar. This seems like a rendering bug in Chrome on Linux.

**Comment by cztomczak** [comment]
Maybe a font missing

**Pull request merged**
