### PR TITLE
Bugfix: Crashes if a header is `hasOwnProperty`

### PR DESCRIPTION
**Pull request by tomekwi**
True story: <https://github.com/1-liners/1-liners/commit/c087021>.

### CODE REVIEW

**Comment by tomekwi** [comment]
:bell: any feedback guys? Can I improve the PR somehow?

**Comment by jez** [comment]
I'm basically fine with it, but I'd like @thlorenz to give a :+1: .

At the very least it could use a one line comment. This isn't exactly obvious unless you're looking at the diff.

**Comment by tomekwi** [comment]
Yes sir!

**Comment by thlorenz** [comment]
LGTM except this needs a test that fails without that fix and now passes.
That also makes clearer what cases this fixes.
Thanks.

**Comment by tomekwi** [comment]
There you go Thorsten :)

**Comment by thlorenz** [comment]
LGTM, please squash into one commit and @jez or I can merge to master and I'll publish a patch.
Thanks.

**Comment by tomekwi** [comment]
:checkered_flag:

**Comment by tomekwi** [comment]
Thanks for merging. Could you please release?

**Comment by thlorenz** [comment]
Published as `0.14.1`. Thanks for the fix.

**Comment by tomekwi** [comment]
:+1:

**Pull request closed without merging**
