### PR TITLE
Add unit test for skipping(Handle file skipping internally #143)

### PR DESCRIPTION
**Pull request by wolfcon**
#143

### CODE REVIEW

**Comment by wolfcon** [comment]
@AndrewSouthpaw PR this test?🧐
#143 has been already accepted.

**Review by AndrewSouthpaw — APPROVED** [review]

**Comment by AndrewSouthpaw** [comment]
Oops thanks, missed this 😅

**Comment by AndrewSouthpaw** [comment]
Next time, I think it'd be better to roll them into the same PR.

**Comment by wolfcon** [comment]
> Next time, I think it'd be better to roll them into the same PR.

That would great. I just can't commit his PR. So... merge his commit and recreate this PR.

**Comment by AndrewSouthpaw** [comment]
Oh! Sorry I didn't notice you weren't the same person. My bad!

Seems like it's all squared away now.

**Comment by wolfcon** [comment]
nm🤪

**Pull request merged**
